### ISSUE TITLE
What hardware do you use this with?

### ISSUE THREAD

**Issue by neuhaus** [VGCH/Radiation_on_ESP8266-1#1]

**Comment by VGCH** [comment]
Geiger tube SI-180G and ESP8266 module

**Comment by neuhaus** [comment]
But which geiger counter? One like http://search.ebay.com/151823793908 ?

**Comment by VGCH** [comment]
You can use this geiger tube http://m.ebay.com/itm/SBM-20-Geiger-counter-NEW-for-Dosimeter-Radiometer-an-STS-5-Test-/280865770387?nav=SEARCH

**Comment by VGCH** [comment]
I use this scheme to Geiger http://vrtp.ru/screenshots/2420_geiger.GIF

**Comment by neuhaus** [comment]
OK thanks
